name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Download and set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: "33.0.0"
        target: android-33

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build without tests
      run: ./gradlew assembleDebug

    - name: Build APK (Release version without tests)
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
