name: Deploy Javadoc

on:
  push:
    branches:
      - master

jobs:
  publish_javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create local.properties
        env:
          MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
        run: echo "MAPS_API_KEY=$MAPS_API_KEY" >> local.properties

      - name: Setup Java JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      - name: Give gradlew Execute Permission
        run: chmod +x gradlew

      - name: Build App (fixes some dependency errors with Javadoc)
        run: ./gradlew build --parallel -x test

      - name: Create Javadoc
        run: ./gradlew generateReleaseJavadoc

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc
