name: Deploy Javadoc

on:
  push:
    branches:
      - main
    paths:
      - 'app/src/main/java/**' # Only trigger when changes are made in the main Java source directory
      - 'README.md'            # Example additional files to trigger workflow

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Filter to run only on the main branch

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Generate Javadoc
      run: ./gradlew javadoc

    - name: Deploy Javadoc to GitHub Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Target branch for GitHub Pages
        folder: app/build/docs/javadoc  # Path to the Javadoc output
        clean: true  # Clean the target branch before deployment

    - name: Confirm Javadoc generation
      if: success()
      run: echo "Javadoc generated and deployed to GitHub Pages."
